config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  #get 'welcome/index'
  resources :coins

  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
    belongs_to :mining_type #, optional: true
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
    has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale

    def set_locale
        if params[:locale]
            cookies[:locale] = params[:locale]
        end
        if cookies[:locale]
            if I18n.locale != cookies[:locale]
                I18n.locale = cookies[:locale]
            end
        end
    end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: [:show, :edit, :update, :destroy]
  before_action :set_mining_type_options, only: [:new, :create, :edit, :update]

  # GET /coins
  # GET /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1
  # GET /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins
  # POST /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: 'Moeda CRIADA com sucesso.' }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1
  # PATCH/PUT /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: 'Moeda EDITADA com sucesso.' }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1
  # DELETE /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: 'Moeda DELETADA com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    def set_mining_type_options
      @mining_type_options = MiningType.all.pluck( :description, :id )
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: [:show, :edit, :update, :destroy]

  # GET /mining_types
  # GET /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1
  # GET /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types
  # POST /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to @mining_type, notice: 'Mining type was successfully created.' }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1
  # PATCH/PUT /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to @mining_type, notice: 'Mining type was successfully updated.' }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1
  # DELETE /mining_types/1.json
  def destroy
    @mining_type.destroy
    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: 'Mining type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @nome = params[:nome]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def dateBR(dateUS)
        dateUS.strftime("%d/%m/%Y")
    end

    def appLocale
        I18n.locale == :en ? "Inglês" : "Português do Brasil"
    end

    def railsEnv
        if Rails.env.development?
            "Desenvolvimento"
        elsif Rails.env.production?
            "Produção"
        else
            "Teste"
        end
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-3">
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_field :description, class: "form-control", placeholder: "ex.: Bitcoin" %>
    </div>

    <div class="form-group">
      <%= form.label :acronym %>
      <%= form.text_field :acronym, class: "form-control", placeholder: "ex.: BTC" %>
    </div>

    <div class="form-group">
      <%= form.label :url_image %>
      <%= form.text_field :url_image, class: "form-control", placeholder: "ex.: https://image.com/img.png" %>
    </div>

    <div class="form-group">
    <%= form.label :mining_type %>
    <%= form.select("mining_type_id", @mining_type_options, {include_blank: "Selecione"}, class: "form-control") %>
    </div>
    <br>
    <div class="actions">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1><%= t('edit.coin') %></h1>
<%= render 'form', coin: @coin %>
<br>
<div class="col-3">
<%= link_to t('links.show'), @coin, class: 'btn btn-info' %>
<%= link_to t('buttons.back'), coins_path, class: "btn btn-secondary" %>
</div>

app/views/coins/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= Coin.model_name.human(count: @coins.count) %></h1>

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th><%= @coins.human_attribute_name(:description) %></th>
      <th><%= @coins.human_attribute_name(:acronym) %></th>
      <th><%= @coins.human_attribute_name(:url_image) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td><%= image_tag coin.url_image, witdh:25, height:25 %></td>
        <td><%= link_to t('links.show'), coin %></td>
        <td><%= link_to t('links.edit'), edit_coin_path(coin) %></td>
        <td><%= link_to t('links.delete'), coin, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('buttons.new'), new_coin_path, class: "btn btn-primary" %>
<%= link_to t('buttons.back'), root_path, class: "btn btn-secondary" %>

app/views/coins/new.html.erb
<h1><%= t('new.coin') %></h1>
<%= render 'form', coin: @coin %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-3">
    <div class="form-group">
      <%= label_tag nil, @coin.class.human_attribute_name(:description) %>
      <%= text_field_tag nil, @coin.description, class: "form-control", :readonly => true %>
    </div>

    <div class="form-group">
      <%= label_tag nil, @coin.class.human_attribute_name(:acronym) %>
      <%= text_field_tag nil, @coin.acronym, class: "form-control", :readonly => true %>
    </div>

    <div class="form-group">
      <%= label_tag nil, @coin.class.human_attribute_name(:url_image) %>
      <%= text_field_tag nil, @coin.url_image, class: "form-control", :readonly => true %>
    </div>

    <div class="form-group">
      <%= label_tag nil, @coin.class.human_attribute_name(:mining_type) %>
      <%= text_field_tag nil, @coin.mining_type.description, class: "form-control", :readonly => true %>
    </div>
    <%= link_to t('links.edit'), edit_coin_path(@coin), class: 'btn btn-primary' %>
    <%= link_to t('buttons.back'), coins_path, class: "btn btn-secondary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <section>
        <ul class="nav justify-content-end">
          <li class="nav-item">
            <%= link_to '[HOME]', root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Português', {locale: 'pt-BR'}, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'English', {locale: 'en'}, class: "nav-link" %>
          </li>
        </ul>
      </section>

      <section>
        <%= yield %>
      </section>

      <hr class="my-4">
      
      <section>
        <p><strong><%= t('language') %>:</strong> <%= t('actual_locale') %></p>
        <p><strong><%= t('current_date') %>:</strong> <%= l(Date.today) %></p>
        <p><strong><%= t('developed') %></strong> <%= link_to "Henrique Artur", "https://github.com/passaroroxo", target: "_blank" %></p>
      </section>
    </div>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type, local: true) do |form| %>
  <% if mining_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
      <% mining_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-3">
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_field :description, class: "form-control", placeholder: "ex.: Proof of Work" %>
    </div>

    <div class="form-group">
      <%= form.label :acronym %>
      <br>
      <%= form.text_field :acronym, class: "form-control", placeholder: "ex.: PoW" %>
    </div>
    <br>
    <div class="actions">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/mining_types/edit.html.erb
<h1><%= t('edit.mining_type') %></h1>
<%= render 'form', mining_type: @mining_type %>
<br>
<div class="col-3">
<%= link_to t('links.show'), @mining_type, class: 'btn btn-info' %>
<%= link_to t('buttons.back'), mining_types_path, class: "btn btn-secondary" %>
</div>

app/views/mining_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= MiningType.model_name.human(count: @mining_types.count) %></h1>

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th><%= @mining_types.human_attribute_name(:description) %></th>
      <th><%= @mining_types.human_attribute_name(:acronym) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.description %></td>
        <td><%= mining_type.acronym %></td>
        <td><%= link_to t('links.show'), mining_type %></td>
        <td><%= link_to t('links.edit'), edit_mining_type_path(mining_type) %></td>
        <td><%= link_to t('links.delete'), mining_type, method: :delete, data: { confirm: t('confirmation') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('buttons.new'), new_mining_type_path, class: "btn btn-primary" %>
<%= link_to t('buttons.back'), root_path, class: "btn btn-secondary" %>

app/views/mining_types/new.html.erb
<h1><%= t('new.mining_type') %></h1>
<%= render 'form', mining_type: @mining_type %>

app/views/mining_types/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-3">
    <div class="form-group">
      <%= label_tag nil, @mining_type.class.human_attribute_name(:description) %>
      <%= text_field_tag nil, @mining_type.description, class: "form-control", :readonly => true %>
    </div>

    <div class="form-group">
      <%= label_tag nil, @mining_type.class.human_attribute_name(:acronym) %>
      <%= text_field_tag nil, @mining_type.acronym, class: "form-control", :readonly => true %>
    </div>

    <%= link_to t('links.edit'), edit_mining_type_path(@mining_type), class: 'btn btn-primary' %>
    <%= link_to t('buttons.back'), mining_types_path, class: "btn btn-secondary" %>
</div>

app/views/welcome/_menu.html.erb
<%= link_to "#{Coin.model_name.human}", coins_path, class: "btn btn-primary btn-lg", role: "button" %>
<%= link_to "#{MiningType.model_name.human}", mining_types_path, class: "btn btn-primary btn-lg", role: "button" %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= t('welcome') %>!</h1>
  <p class="lead"><%= t('wel_part_1') %></p>
  <hr class="my-4">
  <p><%= t('wel_part_2') %>:</p>
  <%= render "menu" %>
</div>